<?php
/**
 * Font Awesome 7.0.1 图标名称列表
 * 包含完整的图标名称数组，供图标选择器使用
 * 现在支持带前缀的图标（fas/far/fab）
 */

function getFontAwesomeIcons() {
    return [
        // === SOLID 图标 (fas) - 最常用的基础图标 ===
        'fas fa-folder', 'fas fa-folder-open', 'fas fa-file', 'fas fa-file-alt', 'fas fa-file-code', 
        'fas fa-file-text', 'fas fa-archive', 'fas fa-home', 'fas fa-building', 'fas fa-store', 
        'fas fa-warehouse', 'fas fa-industry', 'fas fa-city', 'fas fa-map-marker-alt', 'fas fa-user', 
        'fas fa-users', 'fas fa-user-friends', 'fas fa-user-tie', 'fas fa-user-graduate', 'fas fa-user-cog',
        'fas fa-heart', 'fas fa-star', 'fas fa-bookmark', 'fas fa-thumbs-up', 'fas fa-award', 'fas fa-trophy', 
        'fas fa-medal', 'fas fa-cog', 'fas fa-tools', 'fas fa-wrench', 'fas fa-hammer', 'fas fa-screwdriver', 
        'fas fa-cogs', 'fas fa-sliders-h', 'fas fa-chart-bar', 'fas fa-chart-line', 'fas fa-chart-pie', 
        'fas fa-poll', 'fas fa-tachometer-alt', 'fas fa-shopping-cart', 'fas fa-shopping-bag', 'fas fa-gift', 
        'fas fa-credit-card', 'fas fa-money-bill-wave', 'fas fa-camera', 'fas fa-image', 'fas fa-images', 
        'fas fa-photo-video', 'fas fa-film', 'fas fa-music', 'fas fa-play', 'fas fa-book', 'fas fa-graduation-cap', 
        'fas fa-school', 'fas fa-university', 'fas fa-chalkboard-teacher', 'fas fa-laptop', 'fas fa-desktop', 
        'fas fa-tablet-alt', 'fas fa-mobile-alt', 'fas fa-server', 'fas fa-database', 'fas fa-globe', 
        'fas fa-network-wired', 'fas fa-wifi', 'fas fa-broadcast-tower', 'fas fa-satellite', 'fas fa-car', 
        'fas fa-bus', 'fas fa-train', 'fas fa-plane', 'fas fa-ship', 'fas fa-rocket', 'fas fa-bicycle', 
        'fas fa-coffee', 'fas fa-utensils', 'fas fa-pizza-slice', 'fas fa-ice-cream', 'fas fa-cocktail', 
        'fas fa-gamepad', 'fas fa-dice', 'fas fa-puzzle-piece', 'fas fa-chess', 'fas fa-headphones', 
        'fas fa-envelope', 'fas fa-phone', 'fas fa-fax', 'fas fa-mail-bulk', 'fas fa-paper-plane', 
        'fas fa-lock', 'fas fa-key', 'fas fa-shield-alt', 'fas fa-fire-extinguisher', 'fas fa-first-aid', 
        'fas fa-calendar', 'fas fa-clock', 'fas fa-stopwatch', 'fas fa-hourglass-half', 'fas fa-bell', 
        'fas fa-lightbulb', 'fas fa-eye', 'fas fa-search', 'fas fa-filter', 'fas fa-sort', 'fas fa-download', 
        'fas fa-upload', 'fas fa-edit', 'fas fa-trash', 'fas fa-plus', 'fas fa-minus', 'fas fa-times', 
        'fas fa-check', 'fas fa-exclamation', 'fas fa-question', 'fas fa-info', 'fas fa-arrow-up', 
        'fas fa-arrow-down', 'fas fa-arrow-left', 'fas fa-arrow-right', 'fas fa-arrow-circle-up', 
        'fas fa-arrow-circle-down', 'fas fa-arrow-circle-left', 'fas fa-arrow-circle-right', 'fas fa-chevron-up', 
        'fas fa-chevron-down', 'fas fa-chevron-left', 'fas fa-chevron-right', 'fas fa-caret-up', 
        'fas fa-caret-down', 'fas fa-caret-left', 'fas fa-caret-right', 'fas fa-angle-double-up', 
        'fas fa-angle-double-down', 'fas fa-angle-double-left', 'fas fa-angle-double-right', 'fas fa-angle-up', 
        'fas fa-angle-down', 'fas fa-angle-left', 'fas fa-angle-right', 'fas fa-bars', 'fas fa-navicon', 
        'fas fa-times-circle', 'fas fa-check-circle', 'fas fa-question-circle', 'fas fa-info-circle', 
        'fas fa-exclamation-circle', 'fas fa-exclamation-triangle', 'fas fa-ban', 'fas fa-plus-circle', 
        'fas fa-minus-circle', 'fas fa-check-square', 'fas fa-times-square', 'fas fa-circle', 'fas fa-square', 
        'fas fa-heart-broken', 'fas fa-thumbs-down', 'fas fa-smile', 'fas fa-frown', 'fas fa-meh', 
        'fas fa-battery-full', 'fas fa-battery-half', 'fas fa-battery-quarter', 'fas fa-battery-empty', 
        'fas fa-battery-three-quarters', 'fas fa-toggle-on', 'fas fa-toggle-off', 'fas fa-wifi', 'fas fa-signal',
        'fas fa-print', 'fas fa-copy', 'fas fa-save', 'fas fa-folder-plus', 'fas fa-folder-minus', 'fas fa-folder-open',
        'fas fa-file-upload', 'fas fa-file-download', 'fas fa-file-alt', 'fas fa-file-code', 'fas fa-file-excel',
        'fas fa-file-word', 'fas fa-file-pdf', 'fas fa-file-image', 'fas fa-file-video', 'fas fa-file-audio',
        'fas fa-file-archive', 'fas fa-qrcode', 'fas fa-barcode', 'fas fa-link', 'fas fa-unlink', 'fas fa-thumbtack',
        'fas fa-paperclip', 'fas fa-sticky-note', 'fas fa-tags', 'fas fa-tag', 'fas fa-tasks', 'fas fa-clipboard',
        'fas fa-clipboard-check', 'fas fa-clipboard-list', 'fas fa-stamp', 'fas fa-cube', 'fas fa-cubes',
        'fas fa-pallet', 'fas fa-sitemap', 'fas fa-braille', 'fas fa-american-sign-language-interpreting',
        'fas fa-deaf', 'fas fa-sign-language', 'fas fa-low-vision', 'fas fa-universal-access', 'fas fa-blind',
        'fas fa-audio-description', 'fas fa-assistive-listening-systems', 'fas fa-wheelchair', 'fas fa-ambulance',
        'fas fa-subway', 'fas fa-train', 'fas fa-bus-alt', 'fas fa-rocket', 'fas fa-helicopter', 'fas fa-ship',
        'fas fa-fighter-jet', 'fas fa-space-shuttle', 'fas fa-truck', 'fas fa-motorcycle', 'fas fa-bicycle',
        'fas fa-walking', 'fas fa-running', 'fas fa-swimmer', 'fas fa-skating', 'fas fa-skiing', 'fas fa-skiing-nordic',
        'fas fa-snowboarding', 'fas fa-truck-loading', 'fas fa-truck-moving', 'fas fa-shipping-fast', 'fas fa-warehouse',
        'fas fa-box', 'fas fa-boxes', 'fas fa-box-open', 'fas fa-archive', 'fas fa-briefcase', 'fas fa-briefcase-medical',
        'fas fa-suitcase', 'fas fa-suitcase-rolling', 'fas fa-luggage-cart', 'fas fa-shopping-basket', 'fas fa-cart-plus',
        'fas fa-cart-arrow-down', 'fas fa-cash-register', 'fas fa-calculator', 'fas fa-receipt', 'fas fa-credit-card',
        'fas fa-money-check', 'fas fa-money-check-alt', 'fas fa-money-bill-wave-alt', 'fas fa-dollar-sign',
        'fas fa-rupee-sign', 'fas fa-yen-sign', 'fas fa-euro-sign', 'fas fa-pound-sign', 'fas fa-won-sign',
        'fas fa-coins', 'fas fa-piggy-bank', 'fas fa-hand-holding-usd', 'fas fa-hand-holding-water', 'fas fa-hand-holding-heart',
        'fas fa-hand-holding', 'fas fa-hand-holding-medical', 'fas fa-hand-peace', 'fas fa-hand-paper',
        'fas fa-hand-rock', 'fas fa-hand-scissors', 'fas fa-hand-lizard', 'fas fa-hand-spock', 'fas fa-hand-pointer',
        'fas fa-hand-point-up', 'fas fa-hand-point-down', 'fas fa-hand-point-left', 'fas fa-hand-point-right',
        'fas fa-thumbs-up', 'fas fa-thumbs-down', 'fas fa-fist-raised', 'fas fa-hands', 'fas fa-hands-helping',
        'fas fa-handshake', 'fas fa-praying-hands', 'fas fa-balance-scale', 'fas fa-balance-scale-left',
        'fas fa-balance-scale-right', 'fas fa-weight', 'fas fa-weight-hanging', 'fas fa-ruler', 'fas fa-ruler-combined',
        'fas fa-ruler-horizontal', 'fas fa-ruler-vertical', 'fas fa-tape', 'fas fa-thermometer', 'fas fa-thermometer-half',
        'fas fa-thermometer-empty', 'fas fa-thermometer-full', 'fas fa-thermometer-quarter', 'fas fa-thermometer-three-quarters',
        'fas fa-tint', 'fas fa-tint-slash', 'fas fa-sun', 'fas fa-moon', 'fas fa-star', 'fas fa-star-half',
        'fas fa-star-half-alt', 'fas fa-cloud', 'fas fa-cloud-sun', 'fas fa-cloud-moon', 'fas fa-cloud-rain',
        'fas fa-cloud-showers-heavy', 'fas fa-cloud-sun-rain', 'fas fa-cloud-moon-rain', 'fas fa-snowflake',
        'fas fa-bolt', 'fas fa-fire', 'fas fa-fire-alt', 'fas fa-water', 'fas fa-wind', 'fas fa-smog',
        'fas fa-mountain', 'fas fa-volcano', 'fas fa-tree', 'fas fa-leaf', 'fas fa-seedling', 'fas fa-spa',
        'fas fa-umbrella', 'fas fa-umbrella-beach', 'fas fa-cocktail', 'fas fa-glass-martini', 'fas fa-glass-martini-alt',
        'fas fa-glass-whiskey', 'fas fa-wine-glass', 'fas fa-wine-glass-alt', 'fas fa-coffee', 'fas fa-hot-tub',
        'fas fa-bicycle', 'fas fa-campground', 'fas fa-hiking', 'fas fa-compass', 'fas fa-map', 'fas fa-map-marked',
        'fas fa-map-marked-alt', 'fas fa-map-signs', 'fas fa-location-arrow', 'fas fa-crosshairs', 'fas fa-globe',
        'fas fa-globe-africa', 'fas fa-globe-americas', 'fas fa-globe-asia', 'fas fa-globe-europe', 'fas fa-satellite',
        'fas fa-satellite-dish', 'fas fa-broadcast-tower', 'fas fa-wifi', 'fas fa-signal', 'fas fa-phone',
        'fas fa-phone-alt', 'fas fa-phone-slash', 'fas fa-phone-square', 'fas fa-phone-square-alt', 'fas fa-phone-volume',
        'fas fa-mail-bulk', 'fas fa-envelope', 'fas fa-envelope-open', 'fas fa-envelope-open-text', 'fas fa-envelope-square',
        'fas fa-paper-plane', 'fas fa-fax', 'fas fa-newspaper', 'fas fa-address-book', 'fas fa-address-card',
        'fas fa-id-badge', 'fas fa-id-card', 'fas fa-id-card-alt', 'fas fa-passport', 'fas fa-stamp',
        'fas fa-certificate', 'fas fa-award', 'fas fa-medal', 'fas fa-trophy', 'fas fa-gift', 'fas fa-gifts',
        'fas fa-birthday-cake', 'fas fa-cookie', 'fas fa-cookie-bite', 'fas fa-candy-cane', 'fas fa-carrot',
        'fas fa-lemon', 'fas fa-pepper-hot', 'fas fa-apple-alt', 'fas fa-ice-cream', 'fas fa-pizza-slice',
        'fas fa-bacon', 'fas fa-egg', 'fas fa-cheese', 'fas fa-bread-slice', 'fas fa-hamburger', 'fas fa-hotdog',
        'fas fa-sandwich', 'fas fa-fish', 'fas fa-drumstick-bite', 'fas fa-stroopwafel', 'fas fa-cocktail',
        'fas fa-beer', 'fas fa-mug-hot', 'fas fa-coffee', 'fas fa-wine-bottle', 'fas fa-glass-cheers',
        'fas fa-gamepad', 'fas fa-puzzle-piece', 'fas fa-chess', 'fas fa-chess-board', 'fas fa-chess-king',
        'fas fa-chess-queen', 'fas fa-chess-rook', 'fas fa-chess-bishop', 'fas fa-chess-knight', 'fas fa-chess-pawn',
        'fas fa-dice', 'fas fa-dice-one', 'fas fa-dice-two', 'fas fa-dice-three', 'fas fa-dice-four',
        'fas fa-dice-five', 'fas fa-dice-six', 'fas fa-dice-d6', 'fas fa-dice-d20', 'fas fa-headphones',
        'fas fa-headphones-alt', 'fas fa-headset', 'fas fa-microphone', 'fas fa-microphone-alt', 'fas fa-microphone-slash',
        'fas fa-radio', 'fas fa-stereo', 'fas fa-tv', 'fas fa-desktop', 'fas fa-laptop', 'fas fa-laptop-code',
        'fas fa-laptop-house', 'fas fa-laptop-medical', 'fas fa-tablet', 'fas fa-tablet-alt', 'fas fa-mobile',
        'fas fa-mobile-alt', 'fas fa-watch', 'fas fa-clock', 'fas fa-stopwatch', 'fas fa-hourglass',
        'fas fa-hourglass-half', 'fas fa-hourglass-start', 'fas fa-hourglass-end', 'fas fa-calendar',
        'fas fa-calendar-alt', 'fas fa-calendar-check', 'fas fa-calendar-day', 'fas fa-calendar-minus',
        'fas fa-calendar-plus', 'fas fa-calendar-times', 'fas fa-calendar-week', 'fas fa-print', 'fas fa-scanner',
        'fas fa-copy', 'fas fa-save', 'fas fa-file', 'fas fa-file-alt', 'fas fa-file-code', 'fas fa-file-csv',
        'fas fa-file-excel', 'fas fa-file-image', 'fas fa-file-import', 'fas fa-file-export', 'fas fa-file-pdf',
        'fas fa-file-powerpoint', 'fas fa-file-signature', 'fas fa-file-upload', 'fas fa-file-video', 'fas fa-file-word',
        'fas fa-folder', 'fas fa-folder-open', 'fas fa-folder-plus', 'fas fa-folder-minus', 'fas fa-archive',
        'fas fa-box', 'fas fa-boxes', 'fas fa-box-open', 'fas fa-box-tissue', 'fas fa-suitcase', 'fas fa-suitcase-rolling',
        'fas fa-briefcase', 'fas fa-briefcase-medical', 'fas fa-briefcase-clock', 'fas fa-briefcase-dollar',
        'fas fa-briefcase-arrow-right', 'fas fa-briefcase-arrow-left', 'fas fa-briefcase-blank', 'fas fa-briefcase-times',
        'fas fa-backpack', 'fas fa-luggage-cart', 'fas fa-shopping-bag', 'fas fa-shopping-basket', 'fas fa-shopping-cart',
        'fas fa-cart-plus', 'fas fa-cart-arrow-down', 'fas fa-cash-register', 'fas fa-calculator', 'fas fa-receipt',
        'fas fa-credit-card', 'fas fa-credit-card-blank', 'fas fa-credit-card-front', 'fas fa-money-bill',
        'fas fa-money-bill-alt', 'fas fa-money-bill-wave', 'fas fa-money-bill-wave-alt', 'fas fa-money-bills',
        'fas fa-money-check', 'fas fa-money-check-alt', 'fas fa-money-check-dollar', 'fas fa-dollar-sign',
        'fas fa-cents-sign', 'fas fa-percent', 'fas fa-percentage', 'fas fa-coins', 'fas fa-coin', 'fas fa-piggy-bank',
        'fas fa-wallet', 'fas fa-hand-holding-usd', 'fas fa-hand-holding-dollar', 'fas fa-hand-holding-droplet',
        'fas fa-hand-holding-heart', 'fas fa-hand-holding-medical', 'fas fa-hand-holding-seedling', 'fas fa-hand-holding-water',
        'fas fa-hand-holding', 'fas fa-hand-holding-hand', 'fas fa-hand-holding-circle', 'fas fa-handshake',
        'fas fa-handshake-alt', 'fas fa-handshake-slash', 'fas fa-handshake-simple', 'fas fa-handshake-simple-slash',
        'fas fa-thumbs-up', 'fas fa-thumbs-down', 'fas fa-hand-point-up', 'fas fa-hand-point-down', 'fas fa-hand-point-left',
        'fas fa-hand-point-right', 'fas fa-hand-pointer', 'fas fa-hand-paper', 'fas fa-hand-peace', 'fas fa-hand-rock',
        'fas fa-hand-scissors', 'fas fa-hand-sparkles', 'fas fa-hand-middle-finger', 'fas fa-hand-horns',
        'fas fa-hand-fist', 'fas fa-hand-back-fist', 'fas fa-hand-dots', 'fas fa-hand', 'fas fa-hands',
        'fas fa-hands-helping', 'fas fa-hands-asl-interpreting', 'fas fa-hands-bound', 'fas fa-hands-bubbles',
        'fas fa-hands-clapping', 'fas fa-hands-holding', 'fas fa-hands-holding-child', 'fas fa-hands-holding-circle',
        'fas fa-hands-praying', 'fas fa-praying-hands', 'fas fa-hand-receiving', 'fas fa-hand-sparkles',
        'fas fa-heart', 'fas fa-heart-pulse', 'fas fa-heart-broken', 'fas fa-heart-crack', 'fas fa-heart-half',
        'fas fa-heart-half-alt', 'fas fa-heart-half-stroke', 'fas fa-heart-pulse', 'fas fa-heartbeat',
        'fas fa-star', 'fas fa-star-half', 'fas fa-star-half-alt', 'fas fa-star-half-stroke', 'fas fa-star-of-david',
        'fas fa-star-of-life', 'fas fa-award', 'fas fa-medal', 'fas fa-trophy', 'fas fa-certificate',
        'fas fa-certificate', 'fas fa-diploma', 'fas fa-graduation-cap', 'fas fa-school', 'fas fa-university',
        'fas fa-chalkboard', 'fas fa-chalkboard-teacher', 'fas fa-chalkboard-user', 'fas fa-chalkboard-simple',
        'fas fa-book', 'fas fa-book-open', 'fas fa-book-open-reader', 'fas fa-book-quran', 'fas fa-book-bible',
        'fas fa-book-atlas', 'fas fa-book-journal-whills', 'fas fa-book-dead', 'fas fa-book-medical', 'fas fa-book-law',
        'fas fa-bookmark', 'fas fa-books', 'fas fa-scroll', 'fas fa-scroll-old', 'fas fa-scroll-torah', 'fas fa-torah',
        'fas fa-newspaper', 'fas fa-notebook', 'fas fa-note-sticky', 'fas fa-sticky-note', 'fas fa-file',
        'fas fa-file-arrow-up', 'fas fa-file-arrow-down', 'fas fa-file-audio', 'fas fa-file-chart-column',
        'fas fa-file-check', 'fas fa-file-circle-check', 'fas fa-file-circle-exclamation', 'fas fa-file-circle-info',
        'fas fa-file-circle-minus', 'fas fa-file-circle-plus', 'fas fa-file-circle-question', 'fas fa-file-circle-xmark',
        'fas fa-file-code', 'fas fa-file-contract', 'fas fa-file-csv', 'fas fa-file-excel', 'fas fa-file-export',
        'fas fa-file-heart', 'fas fa-file-image', 'fas fa-file-import', 'fas fa-file-invoice', 'fas fa-file-invoice-dollar',
        'fas fa-file-lines', 'fas fa-file-medical', 'fas fa-file-minus', 'fas fa-file-music', 'fas fa-file-pdf',
        'fas fa-file-pen', 'fas fa-file-plus', 'fas fa-file-powerpoint', 'fas fa-file-prescription', 'fas fa-file-shield',
        'fas fa-file-signature', 'fas fa-file-spreadsheet', 'fas fa-file-user', 'fas fa-file-video', 'fas fa-file-waveform',
        'fas fa-file-word', 'fas fa-file-zipper', 'fas fa-file-archive', 'fas fa-file-circle-check', 'fas fa-file-circle-xmark',
        'fas fa-file-edit', 'fas fa-file-exclamation', 'fas fa-file-minus', 'fas fa-file-plus', 'fas fa-file-search',
        'fas fa-file-times', 'fas fa-file-check', 'fas fa-file-excel', 'fas fa-file-export', 'fas fa-file-image',
        'fas fa-file-import', 'fas fa-file-pdf', 'fas fa-file-powerpoint', 'fas fa-file-signature', 'fas fa-file-upload',
        'fas fa-file-video', 'fas fa-file-word', 'fas fa-file-archive', 'fas fa-qrcode', 'fas fa-barcode',
        'fas fa-link', 'fas fa-unlink', 'fas fa-chain', 'fas fa-chain-broken', 'fas fa-chain-slash',
        'fas fa-thumbtack', 'fas fa-thumb-tack', 'fas fa-paperclip', 'fas fa-paperclip-vertical', 'fas fa-stapler',
        'fas fa-stamp', 'fas fa-stamp', 'fas fa-file-signature', 'fas fa-signature', 'fas fa-certificate',
        'fas fa-award', 'fas fa-medal', 'fas fa-trophy', 'fas fa-gift', 'fas fa-gifts', 'fas fa-gift-card',
        'fas fa-coins', 'fas fa-coin', 'fas fa-dollar-sign', 'fas fa-usd', 'fas fa-euro-sign', 'fas fa-eur',
        'fas fa-pound-sign', 'fas fa-gbp', 'fas fa-yen-sign', 'fas fa-jpy', 'fas fa-ruble-sign', 'fas fa-rub',
        'fas fa-won-sign', 'fas fa-krw', 'fas fa-rupee-sign', 'fas fa-inr', 'fas fa-shekel-sign', 'fas fa-ils',
        'fas fa-baht-sign', 'fas fa-thb', 'fas fa-peso-sign', 'fas fa-mxn', 'fas fa-peso', 'fas fa-franc-sign',
        'fas fa-chf', 'fas fa-kip-sign', 'fas fa-lak', 'fas fa-manat-sign', 'fas fa-azn', 'fas fa-bitcoin-sign',
        'fas fa-btc', 'fas fa-ethereum', 'fas fa-dogecoin', 'fas fa-credit-card', 'fas fa-credit-card-blank',
        'fas fa-credit-card-front', 'fas fa-money-check', 'fas fa-money-check-dollar', 'fas fa-money-check-alt',
        'fas fa-money-check-dollar-pen', 'fas fa-money-bill', 'fas fa-money-bill-1', 'fas fa-money-bill-1-wave',
        'fas fa-money-bill-wave', 'fas fa-money-bill-transfer', 'fas fa-money-bill-trend-up', 'fas fa-money-bill-wheat',
        'fas fa-money-bills', 'fas fa-money-from-bracket', 'fas fa-money-simple-from-bracket', 'fas fa-piggy-bank',
        'fas fa-pig', 'fas fa-wallet', 'fas fa-cash-register', 'fas fa-calculator', 'fas fa-receipt', 'fas fa-receipt-alt',
        'fas fa-percent', 'fas fa-percentage', 'fas fa-percent-sign', 'fas fa-hand-holding-usd', 'fas fa-hand-holding-dollar',
        'fas fa-coins', 'fas fa-coin', 'fas fa-chart-line', 'fas fa-chart-bar', 'fas fa-chart-area', 'fas fa-chart-pie',
        'fas fa-chart-scatter', 'fas fa-chart-line-down', 'fas fa-chart-line-up', 'fas fa-chart-simple', 'fas fa-chart-waterfall',
        'fas fa-chart-network', 'fas fa-chart-radar', 'fas fa-chart-bullet', 'fas fa-chart-gantt', 'fas fa-chart-histogram',
        'fas fa-chart-scatter-3d', 'fas fa-chart-scatter-bubble', 'fas fa-chart-tree-map', 'fas fa-chart-pyramid',
        'fas fa-chart-venn', 'fas fa-chart-venn-diagram', 'fas fa-chart-candlestick', 'fas fa-chart-ohlc',
        'fas fa-chart-candlestick', 'fas fa-chart-ohlc', 'fas fa-chart-line-up', 'fas fa-chart-line-down',
        'fas fa-chart-area', 'fas fa-chart-pie', 'fas fa-chart-scatter', 'fas fa-chart-bar', 'fas fa-chart-line',
        'fas fa-chart-simple', 'fas fa-chart-network', 'fas fa-chart-radar', 'fas fa-chart-bullet', 'fas fa-chart-gantt',
        'fas fa-chart-histogram', 'fas fa-chart-scatter-3d', 'fas fa-chart-scatter-bubble', 'fas fa-chart-tree-map',
        'fas fa-chart-pyramid', 'fas fa-chart-venn', 'fas fa-chart-venn-diagram', 'fas fa-chart-candlestick',
        'fas fa-chart-ohlc', 'fas fa-chart-candlestick', 'fas fa-chart-ohlc', 'fas fa-chart-line-up', 'fas fa-chart-line-down',
        'fas fa-chart-area', 'fas fa-chart-pie', 'fas fa-chart-scatter', 'fas fa-chart-bar', 'fas fa-chart-line',
        'fas fa-chart-simple', 'fas fa-chart-network', 'fas fa-chart-radar', 'fas fa-chart-bullet', 'fas fa-chart-gantt',
        'fas fa-chart-histogram', 'fas fa-chart-scatter-3d', 'fas fa-chart-scatter-bubble', 'fas fa-chart-tree-map',
        'fas fa-chart-pyramid', 'fas fa-chart-venn', 'fas fa-chart-venn-diagram', 'fas fa-chart-candlestick',
        'fas fa-chart-ohlc', 'fas fa-chart-candlestick', 'fas fa-chart-ohlc'
    ];
}